apiVersion: apps/v1
kind: Deployment
metadata:
  name: buttonclicker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buttonclicker
  template:
    metadata:
      labels:
        app: buttonclicker
    spec:
      containers:
      - name: buttonclicker
        image: {{ .Values.buttonclicker.image.repository }}:{{ .Values.buttonclicker.image.tag }}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always 
