apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buttonclicker-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: buttonclicker-service
            port:
              number: 8080
